version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/project_service"
    target-branch: "develop"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"

  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "develop"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"